'use strict';

/* Codes generated by: http://travistidwell.com/jsencrypt/demo/ */
const fs = require('fs');
const privateKey = fs.readFileSync(rPath('config/auth/private.key'), 'utf-8');
const publicKey = fs.readFileSync(rPath('config/auth/public.key'), 'utf-8');

module.exports = {
    jwt: {
        privateKey,
        publicKey
    },
    cookie: {
        secret: '@@_2020//_SUNS3T_s3cr3T_K3Y_$$',
        options: {
            httpOnly: true,
            maxAge: 20 * 60 * 1000,
            signed: true
        }
    }
};
